### PR TITLE
Subsampling mAP analysis based on lukes data

### PR DESCRIPTION
**Pull request by MerajRamezani**
@ErinWeisbart here is the data for the new supplemental figure based on Luke's data

### CODE REVIEW

**Comment by MerajRamezani** [comment]
@ErinWeisbart The other supplemental figures with associated code

**Comment by ErinWeisbart** [comment]
@MerajRamezani Supplemental Z (the subsampling) doesn't include  the `data_subsample_aggregated_{n}_cells.csv` files. Can you add those? Thanks.

**Comment by MerajRamezani** [comment]
> @MerajRamezani Supplemental Z (the subsampling) doesn't include the `data_subsample_aggregated_{n}_cells.csv` files. Can you add those? Thanks.

@ErinWeisbart They are about 70 mb each so you they might work better on the gallery. I uploaded them to AWS here:
s3://pooled-cell-painting/projects/2018_11_20_Periscope_Calico/workspace/PERISCOPE_2022_LFS/

**Comment by ErinWeisbart** [comment]
Thanks @MerajRamezani ! I made a number of small changes to the notebooks - mainly around keeping naming and outputting structure consistent and cleaning up some of the graph labeling. 
The one major thing is I went ahead and plotted the average mAP by FDR for the whole profile and compartment hits on the same plot, as we discussed in checkin this week. Supplemental_x/outputs/figure_panels/HeLa_DMEM_average_mAP_hits_parsed.png
I'm going to merge now and we can change X, Y, Z to numbers as part of another PR when we relabel many of the figures.

**Pull request merged**
